version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pagamentodb
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" 
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
