version: '3'
services:
  servico-pagamento:
    build: ./servico-pagamento
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq

  servico-notificacao:
    build: ./servico-notificacao
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pagamentodb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
